// Generated by Wrangler by running `wrangler types --env prod`

interface Env {
	ENVIRONMENT: "development" | "production";
	DEV_LINE_CHANNEL_ID: "2011556606";
	PROD_LINE_CHANNEL_ID: "2011556608";
	TDX_PORTAL_URL: "https://tdx.transportdata.tw/";
	MINI_APP_URL: "https://motc-mini-dog.pages.dev/";
	PROJECT_MGMT_URL: "https://ai.studio/apps/0bd118d7-407b-4576-bf5b-e354f697c2cf";
	DEMO_APP_URL: "https://miniapp.line.me/2011556606-KbygvdxR" | "https://miniapp.line.me/2011556608-DKqWK5Ms";
	TRAFFIC_LIFF_URL: "https://miniapp.line.me/2011479506-1DIDNGJQ";
	GOOGLE_FORM_URL: "https://docs.google.com/forms/d/e/1FAIpQLSd84pIjXoYOYO8qAodE6mI-aBfPyMuXoabBWHsw_g2Lu_u6Eg/viewform";
	FEEDBACK_FORM_URL: "https://docs.google.com/forms/d/e/1FAIpQLSeqcp4e4gbc5L8aE5Kc9dtTVo3Q2UxwQdVd8Mh03tC0Iy94yQ/viewform";
	DETECTIVE_LIFF_URL: "https://miniapp.line.me/2011521041-JnfPdXhF" | "https://miniapp.line.me/2011521043-1nCM8mEa";
	DETECTIVE_WEB_URL: "https://motc-mini-dog.pages.dev/search";
	EAGLE_EYE_LIFF_URL: "https://miniapp.line.me/2011551329-VWljb6fv" | "https://miniapp.line.me/2011551331-FmNctgNi";
	EAGLE_EYE_WEB_URL: "https://motc-mini-dog.pages.dev/eagle-eye";
	SENIOR_CARE_LIFF_URL: "https://miniapp.line.me/2011556606-KbygvdxR" | "https://miniapp.line.me/2011556608-DKqWK5Ms";
	GUARDIAN_WEB_URL: "https://motc-mini-dog.pages.dev/guardian";
	APPS_SCRIPT_AUTH_URL: "https://script.google.com/macros/s/AKfycbw7nEwhtQg15fjIglW_533sQXVqDx_Ld3w8bDtRinFkkXLh0NPjhzALwPfcRT8Sss_Hew/exec";
	KNOWN_INTERNAL_USER_IDS: "Uaecf740fc05ef668b671fa90da9c832e,U4b5e0d89e7e372b2fb2cf6fb61a62ec7,U092b7695571f92f0f23c95c04975636b,U48661172c73e0920140b668f2bcf1a3a";
	FEATURE_SILVER_CARE_ENABLED: "true" | "false";
	FEATURE_EAGLE_EYE_ENABLED: "true";
	FEATURE_DETECTIVE_ENABLED: "true";
	FEATURE_PROJECTS_ENABLED: "true";
	LINE_CHANNEL_ID: string;
	LINE_CHANNEL_SECRET: string;
	GEMINI_API_KEY: string;
	NEEDLE_API_URL: string;
}
